{
 "title": "Kafka Topic",
 "tags": [ "kafka" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "label": "prometheus", "query": "prometheus" },
   {
    "name": "topic",
    "query": {
     "query": "kafka_producer_topic_byte_total{topic!~\"_.*|dbz.*\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Connector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Send Rate - Producer",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(connector) (label_replace(kafka_producer_topic_record_send_rate{clientId=~\"connector-producer-(.+)\", topic!~\"_(.+)\"}, \"connector\", \"$1\", \"clientId\", \"(.*)-[0-9]+, topic=(.*)\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Fetch Rate - Consumer",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(connector) (label_replace(kafka_consumer_fetch_manager_records_consumed_rate{clientId=~\"connector-consumer-(.+), topic=(.*)\"}, \"connector\", \"$1\", \"clientId\", \"(.*)-[0-9]+, topic=(.*)\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Topic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Error Records",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(connector) ((kafka_connect_task_error_total_record_failures{namespace=\"sl-data-center\"} - kafka_connect_task_error_total_record_failures{namespace=\"sl-data-center\"} offset 1m) >= 0)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Consumer Records Lag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by(topic) (kafka_consumer_fetch_manager_records_lag{clientId=~\"connector-consumer-(.+)\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Producer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Producer - Topic Record Send Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum by(topic) (label_replace(kafka_producer_topic_record_send_rate{clientId=~\"connector-producer-(.*), topic=${topic}\"}, \"topic\", \"$3\", \"clientId\", \"(.*)-([0-9]+), topic=(.*)\"))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Producer - Topic Byte Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(topic) (label_replace(kafka_producer_topic_byte_rate{clientId=~\"connector-producer-(.*), topic=${topic}\"}, \"topic\", \"$3\", \"clientId\", \"(.*)-([0-9]+), topic=(.*)\"))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Consumer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Consumer - Sink GCS Records rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum by(topic) (label_replace(kafka_consumer_fetch_manager_records_consumed_rate{clientId=~\"connector-consumer-sink_gcs-(.*), topic=(.*)\"}, \"topic\", \"$3\", \"clientId\", \"(.*)-([0-9]+), topic=(.*)\"))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Consumer - Sink GCS Bytes Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(topic) (label_replace(kafka_consumer_fetch_manager_bytes_consumed_rate{clientId=~\"connector-consumer-sink_gcs-(.*), topic=(.*)\"}, \"topic\", \"$3\", \"clientId\", \"(.*)-([0-9]+), topic=(.*)\"))",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}