{
 "title": "Kafka Connect",
 "tags": [ "kafka" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "label": "prometheus", "query": "prometheus" },
   {
    "name": "connector",
    "query": {
     "query": "kafka_connect_connector_task_running_ratio"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Kafka Connect",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Tasks Running Percentage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(connector) (kafka_connect_worker_connector_running_task_count{connector=~\"${connector}\"}) / sum by(connector) (kafka_connect_worker_connector_total_task_count{connector=~\"${connector}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connector tasks status",
   "type": "table",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_connect_connector_status{connector=~\"${connector}\", namespace=\"sl-data-center\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network traffic rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_connect_incoming_byte_rate",
     "legendFormat": "Incoming({{clientId}}, {{pod}})"
    },
    {
     "expr": "kafka_connect_outgoing_byte_rate",
     "legendFormat": "Outgoing({{clientId}}, {{pod}})"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area='heap', namespace=\"sl-data-center\"}",
     "legendFormat": "Used({{pod}})"
    },
    {
     "expr": "jvm_memory_bytes_max{area='heap', namespace=\"sl-data-center\"}",
     "legendFormat": "Maximum({{pod}})"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_current{namespace=\"sl-data-center\"}",
     "legendFormat": "Running ({{pod}})"
    },
    {
     "expr": "jvm_threads_peak{namespace=\"sl-data-center\"}",
     "legendFormat": "Maximum ({{pod}})"
    },
    {
     "expr": "jvm_threads_started_total{namespace=\"sl-data-center\"}",
     "legendFormat": "Started in total ({{pod}})"
    }
   ]
  }
 ]
}