security.protocol=SASL_SSL
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="${SASL_USERNAME}" password="${SASL_PASSWORD}";

# Calling Remote Kafka

# kafka-topics.sh \
#   --command-config kafka-config.properties \
#   --list \
#   --bootstrap-server pkc-1dkx6.ap-southeast-1.aws.confluent.cloud:9092

# kafka-topics.sh \
#   --command-config kafka-config.properties \
#   --create --if-not-exists \
#   --bootstrap-server pkc-1dkx6.ap-southeast-1.aws.confluent.cloud:9092 \
#   --topic flink_example.orders_source \
#   --partitions 1 \
#   --replication-factor 3
