configmaps:
  kafka-connect-env:
    data:
      # Debezium
      BOOTSTRAP_SERVERS:
      GROUP_ID: dbz.connect_1

      CONFIG_STORAGE_TOPIC: dbz.connect_configs
      OFFSET_STORAGE_TOPIC: dbz.connect_offsets
      STATUS_STORAGE_TOPIC: dbz.connect_statuses

      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 3

      CONNECT_CONFIG_PROVIDERS: file,env,secrets,configmaps
      CONNECT_CONFIG_PROVIDERS_FILE_CLASS: org.apache.kafka.common.config.provider.FileConfigProvider
      CONNECT_CONFIG_PROVIDERS_ENV_CLASS: io.strimzi.kafka.EnvVarConfigProvider
      CONNECT_CONFIG_PROVIDERS_SECRETS_CLASS: io.strimzi.kafka.KubernetesSecretConfigProvider
      CONNECT_CONFIG_PROVIDERS_CONFIGMAPS_CLASS: io.strimzi.kafka.KubernetesConfigMapConfigProvider

      CONNECT_SECURITY_PROTOCOL: SASL_SSL
      CONNECT_SASL_MECHANISM: PLAIN
      CONNECT_SASL_JAAS_CONFIG: <REPLACED_BY_SECRET>
      CONNECT_PRODUCER_SECURITY_PROTOCOL: SASL_SSL
      CONNECT_PRODUCER_SASL_MECHANISM: PLAIN
      CONNECT_PRODUCER_SASL_JAAS_CONFIG: <REPLACED_BY_SECRET>
      CONNECT_CONSUMER_SECURITY_PROTOCOL: SASL_SSL
      CONNECT_CONSUMER_SASL_MECHANISM: PLAIN
      CONNECT_CONSUMER_SASL_JAAS_CONFIG: <REPLACED_BY_SECRET>

      SCHEMA_REGISTRY_URL:
      SCHEMA_REGISTRY_BASIC_AUTH_SOURCE: USER_INFO
      SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO: <REPLACED_BY_SECRET>

      # JMX
      JMXHOST: 0.0.0.0
      JMXPORT: 1976
      KAFKA_OPTS: -javaagent:/kafka/etc/jmx_prometheus_javaagent.jar=8080:/kafka/etc/config.yml
      KAFKA_HEAP_OPTS: -Xms512M -Xmx4G
